### Ver home
GET http://localhost:3000/home


### Logear usuario
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Idiarj",
    "password": "16012004"
}

### Cerrar sesion
POST http://localhost:3000/logout


### Registrar usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "nombre": "Mario",
    "apellido": "Gonzalez",
    "username": "MarioG",
    "correo": "lespongo20@gmail.com",
    "password": "lesvoyaponer20"
}